baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "@Home"
    url = "https://ed-orlando07-home.netlify.app/"
[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "CV"
    url = "https://ed-orlando07.netlify.app/pdfs/CV_Orlando.pdf"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/edorlando07/blogdown"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/edorlando07/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 75
    height = 75
    alt = "Logo"

