---
title: "My First Post: Gratitude and Motivation"
author: "Ed Orlando"
date: 2020-05-10
categories: ["R"]
tags: ["R Markdown", "Tableau", "R Studio"]
description: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

First, I want to give a shout out to the individuals I grind it out every day with at **[White Lodging](<https://www.whitelodging.com/>)**.  The team leader **[Adam Hutsler](<https://www.linkedin.com/in/adam-hutsler-a9104038/>)** and BI Manager **[Max Thomas](<https://www.linkedin.com/in/max-thomas-917291a1/>)** are always coming up with creative ways to solve complex problems and create business value using **[Tableau](<https://www.tableau.com/>)** and **[R](<https://rstudio.com/>)**. 

I was also inspired to create this data science blog based on the work performed by **[Matt Dancho](<https://www.linkedin.com/in/mattdancho/>)**.  His online learning platform **[Business Science University](<https://www.business-science.io/>)** (BSU) walks you through how professional data scientists set up, build, and deploy bleeding edge machine learning models using **[R](<https://rstudio.com/>)**.  I have completed the following BSU courses and will officially publish some projects in the upcoming weeks.

* 101-R: Data Science Foundations
* 102-R: Web Applications
* 201-R: Advanced Machine Learning

In addition, another BSU student, **[Jason Dexter](<https://www.linkedin.com/in/jdex/>)**, recently created his blog which gave me motivation to formally document some of my own personal projects.  His blog can be viewed **[here](<https://www.exploringdata.org/>)**.

Lastly, I also want to thank my grad school professors at **[Valparaiso University](<https://www.valpo.edu/>)** including **[Sonja Streuber](<https://www.linkedin.com/in/verbalicon/>)**, **[Karl Schmitt](<https://www.linkedin.com/in/karl-schmitt-83365b29/>)**, and **[James Caristi](<https://www.linkedin.com/in/james-caristi-5049a12/>)**.  Grad school provided a great foundation that helped me learn the math and theory behind various modeling techniques.  They also introduced me to various software platforms including **[R](<https://rstudio.com/>)** and continue to be a valuable resource.

This blog will help me organize my data science projects as well as sharpen my communication skills.  Stay tuned for more posts and analysis.





