---
title: "Spotify Recommendation Model With R"
author: "Ed Orlando"
date: 2020-05-18
categories: ["R"]
tags: ["R Markdown", "tidyverse", "plotly", "recommenderlab", "arules", "arulesViz"]
description: "This blog walks viewers through how to create a playlist recommendation algorithm using recommenderlab and arules packages"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

### Author: Ed Orlando

### Problem Statement

This tutorial shows you how to create a Spotify Recommendation Algorithm using the **recommenderlab()** and **arules()** packages. 

### Load Libraries
To get started, first load the libbraries listed below.

```{r, echo=TRUE, results="hide", warning=FALSE, error=FALSE, message=FALSE}
# Core & Viz
library(tidyverse)
library(tidyquant)
library(plotly)

# Modeling
library(recommenderlab)
library(arules)
library(arulesViz)
```

### Load Data
Data was previously downloaded and organized.  You may view the data [here](https://ed-orlando07.netlify.app/zip_files/Spotify_Playlist.zip)